### ISSUE TITLE
Overriding max-width on label broken in Firefox

### ISSUE THREAD

**Issue by mbierlee** [fabbricadigitale/paper-chip#39]
The CSS rule in paper-chip.html on L256 wins the specificity check over external max-width styling in Firefox:

```css
:host(:not([opened])) #label ::slotted([slot="label"]) {
  @apply --paper-font-common-nowrap;
  max-width: 80px;
}
```

In Chrome it seems to prefer external styling over this internal rule.

Perhaps it's best to assign a CSS variable to this property to let people set their own width requirements or even disable max-width.
